name       : sdl2-mixer
version    : 2.6.2
release    : 12
source     :
    - https://github.com/libsdl-org/SDL_mixer/archive/refs/tags/release-2.6.2.tar.gz : 30c64e23506fcb1699981a297833407bf5bf9d8ab77390e26b26117b4a58bad5
homepage   : https://www.libsdl.org/projects/SDL_mixer/
license    : Zlib
component  : multimedia.library
emul32     : yes
optimize   : speed
summary    : A simple multi-channel audio mixer
description: |
    A simple multi-channel audio mixer
builddeps  :
    - pkgconfig32(flac)
    - pkgconfig32(libmodplug)
    - pkgconfig32(libmpg123)
    - pkgconfig32(opusfile)
    - pkgconfig32(sdl2)
    - pkgconfig32(vorbis)
    - pkgconfig32(zlib)
setup      : |
    %configure --disable-static --prefix=/usr --with-libmodplug
build      : |
    %make
install    : |
    %make_install
