name       : sdl2-mixer
version    : 2.0.1
release    : 4
source     :
    - https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz : 5a24f62a610249d744cbd8d28ee399d8905db7222bf3bdbc8a8b4a76e597695f
license    : Zlib
component  : multimedia.library
emul32     : yes
optimize   : speed
summary    : A simple multi-channel audio mixer
description: |
    A simple multi-channel audio mixer
builddeps  :
    - pkgconfig32(zlib)
    - pkgconfig32(sdl2)
    - pkgconfig32(flac)
    - pkgconfig32(libmodplug)
    - pkgconfig32(vorbis)
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
