name       : sdl2-mixer
version    : 2.0.0
release    : 2
source     :
    - https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.0.tar.gz : a8ce0e161793791adeff258ca6214267fdd41b3c073d2581cd5265c8646f725b
license    : Zlib
summary    : A simple multi-channel audio mixer
description: |
    A simple multi-channel audio mixer
builddeps  :
    - pkgconfig32(zlib)
    - pkgconfig(sdl2)
    - pkgconfig32(sdl2)
    - pkgconfig(flac)
    - pkgconfig32(flac)
    - pkgconfig(libmodplug)
    - pkgconfig32(libmodplug)
    - pkgconfig(vorbis)
    - pkgconfig32(vorbis)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
optimize   : speed
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
