name       : sdl2-mixer
version    : 2.0.4
release    : 10
source     :
    - https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz : b4cf5a382c061cd75081cf246c2aa2f9df8db04bdda8dcdc6b6cca55bede2419
license    : Zlib
component  : multimedia.library
emul32     : yes
optimize   : speed
summary    : A simple multi-channel audio mixer
description: |
    A simple multi-channel audio mixer
builddeps  :
    - pkgconfig32(flac)
    - pkgconfig32(libmodplug)
    - pkgconfig32(libmpg123)
    - pkgconfig32(opusfile)
    - pkgconfig32(sdl2)
    - pkgconfig32(vorbis)
    - pkgconfig32(zlib)
setup      : |
    %configure --disable-static --prefix=/usr --with-libmodplug
build      : |
    %make
install    : |
    %make_install
