name       : sdl2-mixer
version    : 2.0.0
release    : 1
source     :
    - https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.0.tar.gz : a8ce0e161793791adeff258ca6214267fdd41b3c073d2581cd5265c8646f725b
license    : Zlib
summary    : A simple multi-channel audio mixer
description: |
    A simple multi-channel audio mixer
builddeps  :
    - pkgconfig(sdl2)
    - pkgconfig(flac)
    - pkgconfig(libmodplug)
    - pkgconfig(vorbis)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
