name       : sdl2-mixer
version    : 2.6.3
release    : 16
source     :
    - https://github.com/libsdl-org/SDL_mixer/archive/refs/tags/release-2.6.3.tar.gz : 91dd065e9e63f499e5317350b110184b0ba96bc5f63c39b3a9939a136c40c035
homepage   : https://www.libsdl.org/projects/SDL_mixer/
license    : Zlib
component  : multimedia.library
emul32     : yes
optimize   : speed
summary    : A simple multi-channel audio mixer
description: |
    A simple multi-channel audio mixer
builddeps  :
    - pkgconfig32(flac)
    - pkgconfig32(libmodplug)
    - pkgconfig32(libmpg123)
    - pkgconfig32(opusfile)
    - pkgconfig32(sdl2)
    - pkgconfig32(vorbisfile)
setup      : |
    %configure \
        --disable-music-flac-drflac \
        --disable-music-flac-libflac-shared \
        --disable-music-mod-modplug-shared \
        --disable-music-mp3-drmp3 \
        --disable-music-mp3-mpg123-shared \
        --disable-music-ogg-stb \
        --disable-music-ogg-vorbis-shared \
        --disable-music-opus-shared \
        --disable-static \
        --enable-music-flac-libflac \
        --enable-music-mp3-mpg123 \
        --enable-music-ogg-vorbis \
        --prefix=/usr
build      : |
    %make
install    : |
    %make_install
