name       : sdl2-mixer
version    : 2.0.2
release    : 5
source     :
    - https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.2.tar.gz : 4e615e27efca4f439df9af6aa2c6de84150d17cbfd12174b54868c12f19c83bb
license    : Zlib
component  : multimedia.library
emul32     : yes
optimize   : speed
summary    : A simple multi-channel audio mixer
description: |
    A simple multi-channel audio mixer
builddeps  :
    - pkgconfig32(flac)
    - pkgconfig32(libmodplug)
    - pkgconfig32(libmpg123)
    - pkgconfig32(sdl2)
    - pkgconfig32(vorbis)
    - pkgconfig32(zlib)
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
